contents:
  packages:
    - ingress-nginx-controller
    - ingress-nginx-controller-compat

accounts:
  groups:
    - groupname: www-data
      gid: 101
  users:
    - username: www-data
      uid: 101
  run-as: www-data

environment:
  PATH: "$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/luajit/bin:/usr/local/nginx/sbin/"
  LUA_PATH: "/usr/local/share/luajit-2.1.0-beta3/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/lib/lua/?.lua;/usr/lib/lua/?.lua;/usr/share/lua/?.lua"
  LUA_CPATH: "/usr/local/lib/lua/5.1/?.so;/usr/local/lib/lua/?/?.so;/usr/local/lib/lua/?.so;/usr/lib/lua/?.lua;"
  LD_PRELOAD: "/usr/lib/libmimalloc.so"

work-dir:  /etc/nginx

entrypoint:
  cmd: /nginx-ingress-controller
cmd: "/usr/bin/dumb-init ---"

paths:
  - path: /etc/ingress-controller
    type: directory
    permissions: 0o755
    uid: 101
    gid: 101
  - path: /etc/ingress-controller/ssl
    type: directory
    permissions: 0o755
    uid: 101
    gid: 101
    recursive: true
  - path: /etc/ingress-controller/auth
    type: directory
    permissions: 0o755
    uid: 101
    gid: 101
    recursive: true
  - path: /usr/local/
    type: directory
    permissions: 0o755
    uid: 101
    gid: 101
    recursive: true
  - path: /usr/local/
    type: directory
    permissions: 0o755
    uid: 101
    gid: 101
    recursive: true
  - path: /var/lib/
    type: directory
    permissions: 0o755
    uid: 101
    gid: 101
    recursive: true
  - path: /var/lib/nginx/
    type: directory
    uid: 101
    gid: 101
    permissions: 0o755
    recursive: true
  - path: /var/lib/nginx/body
    type: directory
    uid: 101
    gid: 101
    permissions: 0o755
    recursive: true
  - path: /usr/local/nginx
    type: directory
    uid: 101
    gid: 101
    permissions: 0o755
    recursive: true
  - path: /run/nginx
    uid: 101
    gid: 101
    type: directory
    permissions: 0o755
    recursive: true
  - path: /etc/nginx/modules
    uid: 101
    gid: 101
    type: directory
    permissions: 0o755
    recursive: true
  - path: /etc/nginx
    uid: 101
    gid: 101
    type: directory
    permissions: 0o755
    recursive: true
  - path: /usr/local/nginx
    uid: 101
    gid: 101
    type: directory
    permissions: 0o755
    recursive: true
  - path: /opt/modsecurity/
    uid: 101
    gid: 101
    type: directory
    permissions: 0o755
    recursive: true
  - path: /var/log
    uid: 101
    gid: 101
    type: directory
    permissions: 0o755
  - path: /tmp/nginx
    uid: 101
    gid: 101
    type: directory
    permissions: 0o755
    recursive: true
  - path: /usr/lib/libmimalloc.so
    source: /usr/local/lib64/libmimalloc.so
    type: symlink
    uid: 101
    gid: 101
    permissions: 0o755
